version: '3.6'

# Volumes
volumes:
  zookeeper-data:
    driver: local
  zookeeper-log:
    driver: local
  kafka-data:
    driver: local
  elasticsearch-data:
    driver: local

# Networks
networks:
  covid_processor_network:
    driver: bridge

services:
  akhq:
    image: tchiotludo/akhq
    container_name: akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"
    ports:
      - 8088:8080
    links:
      - kafka
    networks:
      - covid_processor_network
      
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - covid_processor_network

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    volumes:
      - kafka-data:/var/lib/kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_NUM_PARTITIONS: 12
      KAFKA_COMPRESSION_TYPE: gzip
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
      KAFKA_JMX_PORT: 9091
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    links:
      - zookeeper
    networks:
      - covid_processor_network


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=covid-tweets-es-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - covid_processor_network


  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.6.2
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - covid_processor_network
      
  # Covid Tweets Ingest
  covid_tweets_ingest:
    image: ssanchez11/covid_tweets_ingest:0.0.1-SNAPSHOT
    container_name: covid_tweets_ingest
    networks:
      - covid_processor_network
      
      
  # Covid Tweets Processor
  covid_tweets_processor:
    image: ssanchez11/covid_tweets_processor:0.0.1-SNAPSHOT
    container_name: covid_tweets_processor
    networks:
      - covid_processor_network

  # Covid Tweets Collector
  covid_tweets_collector:
    image: ssanchez11/covid_tweets_collector:0.0.1-SNAPSHOT
    container_name: covid_tweets_collector
    networks:
      - covid_processor_network

  # Covid Tweets API
  covid_tweets_api:
    image: ssanchez11/covid_tweets_api:0.0.1-SNAPSHOT
    container_name: covid_tweets_api
    ports:
      - 8080:8080
    networks:
      - covid_processor_network
